In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib created a temporary cache directory at C:\Users\pwal9\AppData\Local\Temp\matplotlib-n1oodx9t because the default path (C:\Users\pwal9\.matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.


In [19]:
df = pd.read_csv('Titanic-Dataset.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [20]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
df = df.drop(['Cabin'], axis=1)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

In [25]:
df = df.drop(['PassengerId'], axis=1)
df.head()

Survived  Pclass                                               Name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Embarked  
0    male  22.0      1      0         A/5 21171   7.2500        S  
1  female  38.0      1      0          PC 17599  71.2833        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250        S  
3  female  35.0      1      0            113803  53.1000        S  
4    male  35.0      0      0            373450   8.0500        S

In [27]:
df['Age'] = df['Age'].fillna(df['Age'].mean())


In [28]:
df.isna().sum()

Survived    0
Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    2
dtype: int64

In [31]:
df = df.drop(['Name'],axis = 1)

In [32]:
df = df.drop(['Ticket'],axis = 1)

In [34]:
df['Sex'] = df['Sex'].replace(['male', 'female'], [1,0])
df.head()

C:\Users\pwal9\AppData\Local\Temp\ipykernel_139004\4051429327.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Sex'] = df['Sex'].replace(['male', 'female'], [1,0])


Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    1  22.0      1      0   7.2500        S
1         1       1    0  38.0      1      0  71.2833        C
2         1       3    0  26.0      0      0   7.9250        S
3         1       1    0  35.0      1      0  53.1000        S
4         0       3    1  35.0      0      0   8.0500        S

In [41]:
df['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [42]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df['Embarked'] = df['Embarked'].replace(['S','Q','C'], [1,2,3])

C:\Users\pwal9\AppData\Local\Temp\ipykernel_139004\4174057472.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Embarked'] = df['Embarked'].replace(['S','Q','C'], [1,2,3])


In [43]:
from sklearn.model_selection import train_test_split

x = df.drop(['Survived'], axis=1)
y = df['Survived']

xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.2, random_state=100)

In [45]:

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)
xtrain

array([[ 0.84505322,  0.7243102 , -0.69550063, ..., -0.47440828,
        -0.48578107, -0.58147255],
       [ 0.84505322,  0.7243102 , -1.61570893, ...,  2.05576923,
         0.25965275, -0.58147255],
       [ 0.84505322,  0.7243102 , -0.08202843, ..., -0.47440828,
        -0.48625739,  0.68074835],
       ...,
       [-1.52375737, -1.38062393,  0.68481182, ...,  0.79068047,
         0.95046842,  1.94296924],
       [ 0.84505322, -1.38062393, -0.02841728, ...,  2.05576923,
         0.69119463, -0.58147255],
       [-1.52375737, -1.38062393, -0.00534441, ..., -0.47440828,
         1.14750492, -0.58147255]])

In [47]:
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(xtrain,ytrain)


In [52]:
ypred = model.predict(xtest)
ypred

array([ 0.74230589,  0.69348447,  0.10445816,  0.64584833,  0.20294955,
        0.5835348 ,  0.09914003,  0.3492281 ,  0.94978898,  0.46065355,
        1.07338931,  0.13412176,  0.19598024,  0.49650936,  0.59000105,
        0.19593064,  0.93672732,  0.39507999,  0.37101624,  0.14034643,
        0.08790604,  1.00557438,  0.15250062,  0.64425697,  0.09872106,
        0.0879604 ,  0.70487338,  0.1309676 ,  0.05563144,  0.18295125,
       -0.25742558,  0.73803928,  0.44343086,  0.25724019,  0.99070356,
        0.07025498,  0.86332988,  0.94111584,  0.67958196,  0.08786347,
        0.61124631,  1.03485944,  0.14983673,  0.17808752, -0.25742558,
        0.6596225 ,  0.14039197,  1.05946586,  0.17964572,  0.8488869 ,
        0.1647811 ,  0.26948102,  0.09779071,  0.11022021,  0.09478405,
        0.16423917,  0.06201621,  0.07468089,  0.21771879,  0.28074556,
        0.22016525,  0.33464206,  0.13440374,  0.11875909,  0.25724019,
        0.65043025,  0.14036702,  0.73877686,  0.74834151,  0.04

In [55]:
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(ypred, ytest))

0.2955280417540506


In [56]:
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression().fit(xtrain,ytrain)



In [59]:
ypreds = model1.predict(xtest)
ypreds

array([1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1], dtype=int64)

In [60]:
from sklearn.metrics import accuracy_score
print(accuracy_score(ypreds, ytest))

0.8044692737430168
